### ISSUE TITLE
Provide consistent hook APIs for methods mixed into model classes from connectors

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-datasource-juggler#367]
When a LoopBack model is attached a data source, the underlying connector will mix in a list of methods on the model class. If the connector is backed by one of the databases, the methods are the CRUD operations. At the moment, the juggler only has hard-coded before/after hooks that have serious issues:

1. The before/after hook only allows one handler
2. The triggering of hooks are hard-coded in the lib/dao.js
3. Not all paths are covered

See open issues or pull requests:
- https://github.com/strongloop/loopback-datasource-juggler/pull/363
- https://github.com/strongloop/loopback-datasource-juggler/pull/359
- https://github.com/strongloop/loopback-datasource-juggler/issues/262
- https://github.com/strongloop/loopback-datasource-juggler/issues/202
- https://github.com/strongloop/loopback-datasource-juggler/issues/159
- https://github.com/strongloop/loopback/issues/614
- https://github.com/strongloop/loopback-datasource-juggler/issues/142

Tasks:

 - [x] Finish and land #403
 - [x] Land `before delete` hook #412
 - [x] Update docs draft for `before delete` hook
 - [x] Write documentation for the new hook API.
 - [x] Rename `query` to access (#418) and update docs
 - ~~Clean up change-detection events, let them use the new API - see https://github.com/strongloop/loopback/issues/1048~~
 - ~~Add `test/persistence-hooks.suite.js` to connector tests: Not strictly needed, since all hooks are implemented inside juggler.~~

Out of scope (follow-up):
  - Per-method hooks #397
  - Advance hook use-cases #417

**Comment by bajtos** [comment]
@alFReD-NSH I am starting to work on this today.

>  I assume you guys prefer to use loopback-phase for this.

Not necessarily.

**Comment by STRML** [comment]
What would you like to use, then? It should be a pretty simple impl with
hooks-js.

**Comment by bajtos** [comment]
> @STRML What would you like to use, then? It should be a pretty simple impl with
hooks-js.

First I need to get more familiar with the way how the current hooks work, including various quirky edge-cases. Then I'd like to come up with a proposal how the hooks should work instead and discuss it  here. 

Whether we will end up using hooks-js or a different module is an implementation detail. I'll worry about that after we agree on what is the desired behaviour.

**Comment by bajtos** [comment]
I summarized the current status of hooks in a [gist](https://gist.github.com/bajtos/b8157112452eeaf984c9).

The scope of this story is to fix Model hooks:

 - support arbitrary number of handlers for each hooks
 - inherit handlers when subclassing a model
 - ensure all paths are covered

> The triggering of hooks are hard-coded in the lib/dao.js

There are two reasons explaining the current implementation.

 1. Most hooks are per-event, not per-method. E.g. `validation` and `save` hooks
    are invoked for both `Model.create` and `model.save`.

 2. The CRUD implementation is split between `lib/dao.js` and the connectors. The hooks
   are invoked from the place where the CRUD operation in question is implemented,
   thus `lib/dao.js`.

Ideally, all model hooks should be defined by the connector (datasource).
There should be a common set of hooks shared by all connectors of the same type,
e.g. CRUD hooks for database connectors, request/response hooks for REST/SOAP
connectors, etc. However, I strongly prefer to leave that out of scope
of this story.

@raymondfeng I am not sure what exactly was your intent captured by this item (task), could you please add more details?

> Re: the usage of hooks-js

I quickly checked the module hook-js, I see two major problems:

 - AFAICT, the hooks are wrapping prototype methods only, there is no way
   how to wrap static methods like `PersistedModel.create` or `User.login`

 - Only existing methods can be "hooked". We need to provide "virtual" hooks
   not bound to any particular method, e.g. `save` hook which is invoked from
   various places.

**Comment by bajtos** [comment]
I am not a big fan of automatically adding hooks for every CRUD method implemented by DAO. There are multiple ways how to achieve the same thing, and if the developer don't install hooks for every possible way, then his hook handlers will not work as expected.

For example, there are at least three methods that can create a new model instance (database row): `create`, `updateOrCreate`, `findOrCreate`. Now when the connector provides an optimized implementation of `updateOrCreate` method, model's `create` method is not called and attached `create` hooks are not executed.

IMO, we should define a consistent set of hooks to model the CRUD semantics and implement them explicitly in `lib/dao.js` and/or connectors.

To ensure that all paths are covered even in optimized implementations provided by connectors, we should write a reusable test-suite that can be run from connector tests.

Mockup:

```js
// juggler/test/hooks.js
require('./hooks-suite')(juggler.Memory);

// juggler/test/hooks-suite.js
module.exports = function testModelHooks(connector) {
  describe('Model hooks', function() {
    var app;
    before(function() {
      app = loopback();
      app.dataSource('db', { connector: connector });
      // etc.
    });

    it('fires beforeCreate hook on createOrUpdate', function(done) {
      // etc.
```

**Comment by raymondfeng** [comment]
The methods in dao.js will be mixed into model classes via https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/jutil.js#L32 with proxyFunctions option set to true. We could enable the hooks at this level. If so, it doesn't matter whether the CRUD method is implemented at dao.js or connectors.

We should allow custom methods to be intercepted too.

**Comment by bajtos** [comment]
Even if we enable hooks at the level of mixing CRUD methods into model classes, it will still not solve the problem that the same hook should be shared by multiple methods, right?

> We should allow custom methods to be intercepted too.

That's already possible, right? All you need to do is to wrap the body of the custom method with `trigger('hookName')`.

Perhaps we can provide auto-hooks for all methods (built-in and custom), and then specific hooks like `create` or `save` that must be triggered explicitly. Is that what you would like to get implemented?

**Comment by bajtos** [comment]
Notes from my Friday discussion with @raymondfeng:

Conceptually, there are two kinds of hooks we eventually want to support in the juggler:
 - method-based hooks similar to `hook-js` that allow developers to hook into specific methods
 - intent-based hooks (similar to the current `beforeSave`/`afterSave` hook and friends) that allow developers to intercept CRUD-related actions independently of the specific method that invoke them (e.g. `create`, `save` or `updateOrCreate`).

The scope of this issue is to implement (improve) intent-based hooks. I have created #397 to track method-based hooks.

List of hooks (initial version):

 - `before load` is triggered whenever a datasource is going to be queried for models (`findById`, `find`, etc.). The handler receives the query (filter) object and has the option to modify it, e.g. limit the query to resources owned by the current user.
 - `after load` is triggered when datasource returned data
 - `before save` is triggered before a model instance is going to get persisted (created, updated).
 - `after save` is triggered after a model instance was persisted. 
 - `before validate`, `after validate` - called when a model is validated, this is similar to `before save`/`after save`.
 - `before delete` - called before a model or a list of model instances will be deleted. The handler will receive a filter describing what instances are being deleted and optionally a list of instances if the data is available.
 - `after delete` - called after some model instances were deleted.

We are intentionally not distinguishing between updates and creates, as that distinction is impossible to detect when the datastore provides an optimised atomic `updateOrCreate` implementation.

To support atomic implementations of `findOrCreate`, the hook `before save` must be triggered always, while the hook `after save` is not triggered when the record was found.

**Comment by bajtos** [comment]
Docs draft: https://gist.github.com/bajtos/b8157112452eeaf984c9#file-new-hooks-docs-md

The task to move the draft into confluence: https://github.com/strongloop-internal/scrum-loopback/issues/162

**Comment by bajtos** [comment]
Released as `loopback-datasource-juggler@2.15.0`

**Comment by glesage** [comment]
Awesome!

**Comment by FoysalOsmany** [comment]
@bajtos @raymondfeng Is it possible from any operation hooks to get the request object?

**Comment by bajtos** [comment]
> Is it possible from any operation hooks to get the request object?

@FoysalOsmany not out of the box. You can use [remoting hooks](https://docs.strongloop.com/display/LB/Strong+Remoting#hooks) if you need to access the request object.

In the future, please post questions to our mailing list and/or other public forums, see [instructions](https://github.com/strongloop/loopback/wiki/Questions).
